[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_limit = "18446744073709551615"  
FOUNDRY_GAS_PRICE = 30000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config